// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/post.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "posts";

export interface UpdatePostDto {
  id: string;
  title: string;
  content: string;
}

export interface FindOnePostDto {
  id: string;
}

export interface CreatePostDto {
  title: string;
  content: string;
  authorName: string;
}

export interface Empty {
}

export interface Posts {
  posts: Post[];
}

export interface Post {
  id: string;
  title: string;
  content: string;
  authorName: string;
}

export const POSTS_PACKAGE_NAME = "posts";

export interface PostsServiceClient {
  createPost(request: CreatePostDto): Observable<Post>;

  findAllPosts(request: Empty): Observable<Posts>;

  findOnePost(request: FindOnePostDto): Observable<Post>;

  updatePost(request: UpdatePostDto): Observable<Post>;

  removePost(request: FindOnePostDto): Observable<Post>;
}

export interface PostsServiceController {
  createPost(request: CreatePostDto): Promise<Post> | Observable<Post> | Post;

  findAllPosts(request: Empty): Promise<Posts> | Observable<Posts> | Posts;

  findOnePost(request: FindOnePostDto): Promise<Post> | Observable<Post> | Post;

  updatePost(request: UpdatePostDto): Promise<Post> | Observable<Post> | Post;

  removePost(request: FindOnePostDto): Promise<Post> | Observable<Post> | Post;
}

export function PostsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPost", "findAllPosts", "findOnePost", "updatePost", "removePost"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PostsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PostsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POSTS_SERVICE_NAME = "PostsService";
